plugins {
    id 'com.android.application'
}

android {
    namespace 'de.notizen.android'
    compileSdk 34

    defaultConfig {
        applicationId 'de.notizen.android'
        minSdk 23
        targetSdk 34
        versionCode 116
        versionName '1.0.116-java-android-nativ'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'org.commonmark:commonmark:0.28.0'
    implementation 'org.commonmark:commonmark-ext-autolink:0.28.0'
    implementation 'org.nibor.autolink:autolink:0.12.0'
    implementation 'org.commonmark:commonmark-ext-gfm-strikethrough:0.28.0'
    implementation 'org.commonmark:commonmark-ext-gfm-tables:0.28.0'
    implementation 'org.commonmark:commonmark-ext-gfm-alerts:0.28.0'
    implementation 'org.commonmark:commonmark-ext-footnotes:0.28.0'
    implementation 'org.commonmark:commonmark-ext-heading-anchor:0.28.0'
    implementation 'org.commonmark:commonmark-ext-ins:0.28.0'
    implementation 'org.commonmark:commonmark-ext-task-list-items:0.28.0'
    implementation 'org.commonmark:commonmark-ext-image-attributes:0.28.0'
    implementation 'org.commonmark:commonmark-ext-yaml-front-matter:0.28.0'
}
