package de.notizen.android.core;

public final class LegacyDesktopNote {
    public static final int BORDER_LEFT=12,BORDER_TOP=32,BORDER_WIDTH_PAD=26,BORDER_HEIGHT_PAD=48,HEADER_HEIGHT=40,HEADER_BUTTON_WIDTH=36,BOTTOM_HOTZONE_HEIGHT=40,MIN_AUTOSIZE_HEIGHT=111,AUTORESIZE_STEP=10,AUTORESIZE_SCROLL_PAD=6,AUTORESIZE_WORK_AREA_PAD=11,AUTORESIZE_IDLE_MS=400,SCREEN_EDGE_MARGIN=80,MOUSE_TOLERANCE=3;
    public static final String ACTION_MOVE="move",ACTION_RESIZE="resize",ACTION_HIDE="hide",ACTION_CLOSE="close",ACTION_HIDE_ZONE="hide-zone",ACTION_CLOSE_ZONE="close-zone",CURSOR_MOVE="size-all",CURSOR_RESIZE="size-nwse",CURSOR_ARROW="arrow",CURSOR_HIDE="pan-south";
    private LegacyDesktopNote() {}
    public static final class Rect { public final int x,y,width,height; public Rect(int x,int y,int width,int height){this.x=x;this.y=y;this.width=width;this.height=height;} @Override public boolean equals(Object o){ if(!(o instanceof Rect))return false; Rect r=(Rect)o; return x==r.x&&y==r.y&&width==r.width&&height==r.height;} @Override public int hashCode(){int h=x;h=31*h+y;h=31*h+width;h=31*h+height;return h;} @Override public String toString(){return "Rect("+x+","+y+","+width+","+height+")";} }
    public static boolean autoResizeCanGrow(Rect r,int waW,int waH){return autoResizeCanGrow(r,waW,waH,AUTORESIZE_WORK_AREA_PAD);} public static boolean autoResizeCanGrow(Rect r,int waW,int waH,int pad){return r!=null&&r.width<waW-r.x-pad&&r.height<waH-r.y-pad;}
    public static Rect autoResizeShrinkStep(Rect r){return autoResizeShrinkStep(r,AUTORESIZE_STEP,MIN_AUTOSIZE_HEIGHT);} public static Rect autoResizeShrinkStep(Rect r,int step,int minH){ if(r==null)return new Rect(0,0,1,Math.max(1,minH)); return new Rect(r.x,r.y,clampPositive(r.width-step),Math.max(minH,r.height-step)); }
    public static Rect autoResizeGrowBothStep(Rect r,int waW,int waH){return autoResizeGrowBothStep(r,waW,waH,AUTORESIZE_STEP,AUTORESIZE_WORK_AREA_PAD);} public static Rect autoResizeGrowBothStep(Rect r,int waW,int waH,int step,int pad){ if(r==null)return new Rect(0,0,1,1); int mw=Math.max(1,waW-r.x-pad),mh=Math.max(1,waH-r.y-pad); if(!autoResizeCanGrow(r,waW,waH,pad))return r; return new Rect(r.x,r.y,Math.min(mw,r.width+step),Math.min(mh,r.height+step)); }
    public static Rect autoResizeGrowWidthStep(Rect r,int waW,int waH){return autoResizeGrowWidthStep(r,waW,waH,AUTORESIZE_STEP,AUTORESIZE_WORK_AREA_PAD);} public static Rect autoResizeGrowWidthStep(Rect r,int waW,int waH,int step,int pad){ if(r==null)return new Rect(0,0,1,1); int mw=Math.max(1,waW-r.x-pad); if(!autoResizeCanGrow(r,waW,waH,pad))return r; return new Rect(r.x,r.y,Math.min(mw,r.width+step),r.height); }
    public static int opacityPercentForTransparencyPercent(Object value){ int t; try{t=Integer.parseInt(String.valueOf(value));}catch(Exception e){t=0;} t=Math.max(0,Math.min(90,t)); return Math.max(10,Math.min(100,100-t)); }
    public static String[][] transparencyMenuOptions(){ String[][] out=new String[10][2]; int i=0; for(int t=90;t>=0;t-=10){out[i][0]=t+" %";out[i][1]=String.valueOf(opacityPercentForTransparencyPercent(t));i++;} return out; }
    public static Rect hoverGeometry(Rect r){ if(r==null)return new Rect(-BORDER_LEFT,-BORDER_TOP,BORDER_WIDTH_PAD+1,BORDER_HEIGHT_PAD+1); return new Rect(r.x-BORDER_LEFT,r.y-BORDER_TOP,r.width+BORDER_WIDTH_PAD,r.height+BORDER_HEIGHT_PAD); }
    public static Rect hiddenBorderGeometry(Rect r){ if(r==null)return new Rect(BORDER_LEFT,BORDER_TOP,1,1); return new Rect(r.x+BORDER_LEFT,r.y+BORDER_TOP,clampPositive(r.width-BORDER_WIDTH_PAD),clampPositive(r.height-BORDER_HEIGHT_PAD)); }
    public static Rect show2Geometry(Rect r){return hiddenBorderGeometry(r);} public static Rect editorRect(int w,int h,boolean expanded){return expanded?new Rect(BORDER_LEFT,BORDER_TOP,clampPositive(w-BORDER_WIDTH_PAD),clampPositive(h-BORDER_HEIGHT_PAD)):new Rect(0,0,clampPositive(w),clampPositive(h));}
    public static Rect labelGeometry(int windowWidth,int labelWidth,int labelHeight){ int x=windowWidth/2-labelWidth/2; if(x<HEADER_BUTTON_WIDTH+1)x=HEADER_BUTTON_WIDTH+1; int mw=Math.max(1,windowWidth-70); return new Rect(x,10,Math.min(mw,Math.max(1,labelWidth)),Math.max(1,labelHeight)); }
    public static String titleHitAction(int x,int y,int width){return mouseDownAction(x,y,width,true);} public static String mouseDownAction(int x,int y,int width,boolean left){ if(left&&y<HEADER_HEIGHT){ if(x>Math.max(0,width-HEADER_BUTTON_WIDTH))return ACTION_CLOSE; if(x<HEADER_BUTTON_WIDTH)return ACTION_HIDE; } return ACTION_MOVE; }
    public static String mouseMoveAction(int x,int y,int w,int h){ if(y>h-BOTTOM_HOTZONE_HEIGHT){ if(x>w-HEADER_BUTTON_WIDTH)return ACTION_RESIZE; return ACTION_MOVE;} if(y<HEADER_HEIGHT){ if(x>w-HEADER_BUTTON_WIDTH)return ACTION_CLOSE_ZONE; if(x<HEADER_BUTTON_WIDTH)return ACTION_HIDE_ZONE;} return ACTION_MOVE; }
    public static String cursorForMoveAction(String action){ if(ACTION_RESIZE.equals(action))return CURSOR_RESIZE; if(ACTION_CLOSE_ZONE.equals(action))return CURSOR_ARROW; if(ACTION_HIDE_ZONE.equals(action))return CURSOR_HIDE; return CURSOR_MOVE; }
    public static Rect moveGeometry(int mouseX,int mouseY,int offX,int offY,int w,int h){return new Rect(mouseX-offX,mouseY-offY,clampPositive(w),clampPositive(h));} public static Rect resizeGeometry(int winX,int winY,int mouseX,int mouseY){return new Rect(winX,winY,clampPositive(mouseX-winX),clampPositive(mouseY-winY));}
    public static Rect clampToWorkArea(Rect r,int waW,int waH){ if(r==null)return new Rect(0,0,1,1); return new Rect(Math.min(r.x,Math.max(0,waW-SCREEN_EDGE_MARGIN)),Math.min(r.y,Math.max(0,waH-SCREEN_EDGE_MARGIN)),r.width,r.height); }
    public static boolean pointOutside(Rect r,int px,int py){ return r==null||px+MOUSE_TOLERANCE>=r.x+r.width||px-MOUSE_TOLERANCE<=r.x||py+MOUSE_TOLERANCE>=r.y+r.height||py-MOUSE_TOLERANCE<=r.y; }
    public static double opacityForActive(Object stored){ clampOpacity(stored); return 1.0; } public static double opacityForInactive(Object stored){return clampOpacity(stored);} private static double clampOpacity(Object v){ double o; try{o=Double.parseDouble(String.valueOf(v));}catch(Exception e){o=0.85;} return Math.max(0.1,Math.min(1.0,o)); } private static int clampPositive(int v){return Math.max(1,v);} }
